---
node_ufw_rules:
  - port: "{{ stellar.fullnode.ports.captive_core_p2p_port }}"
    proto: tcp
    rule: allow
    from: any
    comment: captive_core_p2p_port

  - port: "{{ stellar.fullnode.ports.listen_port }}"
    proto: tcp
    rule: allow
    from: amplifier.axelar.mainnet.encapsulate.xyz
    comment: listen_port
