---
# maintains mainnet inventory grouped by project names
all:
  vars:
    env: mainnet
  children:
    stellar:
      hosts:
        fullnode.stellar.mainnet.encapsulate.xyz:
          type: fullnode
