---
- name: Create Docker container and copy binary
  vars:
    container_name: stellar_core
  block:
    - name: Create temporary container for binary extraction
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: "{{ stellar.fullnode.core.source_url }}:{{ stellar.fullnode.core.version }}"
        state: present
        recreate: true

    - name: Copy binary
      ansible.builtin.shell: >
        docker cp {{ container_name }}:/usr/bin/{{ node_captive_core_default_binary_name }} {{ node_bin_dir }}/{{ node_captive_core_default_binary_name }}
      args:
        executable: /bin/bash
      register: copy_result
      changed_when: copy_result.rc == 0
      failed_when:
        - copy_result.rc != 0
        - "'No such container' in copy_result.stderr"
      notify:
        - Restart service

    - name: Ensure binary has the correct permissions
      ansible.builtin.file:
        path: "{{ node_bin_dir }}/{{ node_captive_core_default_binary_name }}"
        owner: root
        group: root
        mode: "0755"
      notify:
        - Restart service

  always:
    - name: Remove container
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: absent
